name: 'Release Application'

on:
  push: 
    branches: [master]
jobs:
  release-uat:
    name: Publish UAT Update
    #if: github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    steps:
      - name: PR Number
        run: |
          echo PR #${{ github.event.number }} has been merged
      - name: Checkout
        uses: actions/checkout@master
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Bump Version
        run: |
          VERSION=$(npm version patch --no-git-tag-version) \
          echo ::set-output name=tag::prod-$VERSION
      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            package.json
          commit-message: Updates the front end version ${{ steps.vars.outputs.tag }}
          ref: refs/heads/master
      - name: Tag Commit
        uses: EndBug/latest-tag@latest
        with:
          tag-name:  "${{ steps.vars.outputs.tag }}"
          description: 'Updates the front end to ${{ steps.vars.outputs.tag }}'
