name: 'Release Application'

on:
  pull_request:
    types: [closed]
    branches: ['master']
jobs:
  release-uat:
    name: Publish UAT Update
    if: github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    steps:
      - name: PR Number
        run: |
          echo PR #${{ github.event.number }} has been merged
      - name: Checkout
        uses: actions/checkout@master
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Bump Version
        run: npm version patch --no-git-tag-version
      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            package.json
          commit-message: Committing ./package.json
          ref: refs/heads/UAT
      - name: Set Version Variable
        run: VERSION=$(npm version)
      - name: Tag Commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: 'uat-'
          message: 'Updates the front end to $TAG'
